config/routes.rb
Rails.application.routes.draw do

  root 'store#index', as: 'store'

  resources :items, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :users, only: [:show]
  resources :carts
  resources :line_items, only: [:create]
  resources :orders, only: [:show]

  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

end

app/models/order.rb
class Order < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>

<% if notice %>
  <p><%= notice %></p> 
<% end %>

<% current_cart.line_items.each do |line_item| %>
  <p><%= link_to line_item.item.title, item_path(line_item.item) %> | <%= number_to_currency(line_item.item.price) %> | Quantity: <%= line_item.quantity %> | <% if line_item.item.inventory < 5 %>
    <strong>There are only <%= line_item.item.inventory %> left in stock.</strong>
  <% end %> </p>
<% end %>

<p>Order total: <strong><%= number_to_currency(current_cart.total) %></strong> </p>

<%= button_to 'Checkout', checkout_path %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <%= @category.title %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<ul>
<% @category.items.each do |item| %>
    <li><%= link_to item.title, item_path(item) %></li>
<% end %>
</ul>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<h2>$ <%= @item.price %></h2>

app/views/layouts/_header.html.erb
<nav class="">
    <ul>
        <li> <%= link_to "Store Home", store_path %> </li>
        <% if !!@cart %>
          <li> <%= link_to "Cart", cart_path(current_cart) %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFlatironStore</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/orders/show.html.erb
<% if notice %>
  <p><%= notice %></p> 
<% end %>

Order Status: <%= @order.status %>

app/views/store/index.html.erb
<% @categories.each do |category| %>
  <%= link_to category.title, category_path(category) %>
<% end %>

<% @items.each do |item| %>
  <p><%= item.title %> | <%= number_to_currency(item.price) %> | <%= button_to 'Add to Cart', line_items_path(item_id: item) %></p>
<% end %>